command: ["python", "main.py"]

env:
  - name: 'SALESFORCE_USERNAME'
    value: ''
  - name: 'SALESFORCE_PASSWORD'
    value: ''
  - name: 'SALESFORCE_INSTANCE_URL'
    value: ''
  - name: 'SALESFORCE_CHANGE_EVENT_CHANNEL' # Optional, defaults to "ChangeEvents"
    value: ''
  - name: 'DATABRICKS_WORKSPACE_URL'
    value: ''
  - name: 'DATABRICKS_CLIENT_ID' # OAuth Service Principal client ID
    value: ''
  - name: 'DATABRICKS_CLIENT_SECRET' # OAuth Service Principal client secret
    value: ''
  - name: 'DATABRICKS_INGEST_ENDPOINT'
    value: ''
  - name: 'DATABRICKS_ZEROBUS_TARGET_TABLE'
    value: ''
  - name: 'DATABRICKS_SQL_ENDPOINT' # Optional
    value: ''

  # - name: 'ZEROBUS_FLUSH_TIMEOUT_MS' # Optional
  #   value: '900000'
  # - name: 'ZEROBUS_SERVER_ACK_TIMEOUT_MS' # Optional
  #   value: '120000'
  # - name: 'ZEROBUS_RECOVERY_RETRIES' # Optional
  #   value: '5'
  # - name: 'ZEROBUS_RECOVERY_TIMOUT_MS' # Optional
  #   value: '10000'
  # - name: 'ZEROBUS_RECOVERY_BACKOFF_MS' # Optional
  #   value: '3000'
  # - name: 'ZEROBUS_MAX_INFLIGHT_RECORDS' # Optional
  #   value: '75000'
