// Row format written to the Zerobus target Delta table.
//
// proto2 is required by Zerobus. Fields 1-16 are the original schema shared
// with the Python service and go_salesforce_zerobus_cgo; never renumber or
// retype them. New fields are additive and map to nullable Delta columns.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: salesforce_events.proto

package eventpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SalesforceEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EventId            *string                `protobuf:"bytes,1,opt,name=event_id,json=eventId" json:"event_id,omitempty"`
	SchemaId           *string                `protobuf:"bytes,2,opt,name=schema_id,json=schemaId" json:"schema_id,omitempty"`
	ReplayId           *string                `protobuf:"bytes,3,opt,name=replay_id,json=replayId" json:"replay_id,omitempty"` // hex-encoded Salesforce replay ID
	Timestamp          *int64                 `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`              // ingest time, epoch millis
	ChangeType         *string                `protobuf:"bytes,5,opt,name=change_type,json=changeType" json:"change_type,omitempty"`
	EntityName         *string                `protobuf:"bytes,6,opt,name=entity_name,json=entityName" json:"entity_name,omitempty"`
	ChangeOrigin       *string                `protobuf:"bytes,7,opt,name=change_origin,json=changeOrigin" json:"change_origin,omitempty"`
	RecordIds          []string               `protobuf:"bytes,8,rep,name=record_ids,json=recordIds" json:"record_ids,omitempty"`
	ChangedFields      []string               `protobuf:"bytes,9,rep,name=changed_fields,json=changedFields" json:"changed_fields,omitempty"`
	NulledFields       []string               `protobuf:"bytes,13,rep,name=nulled_fields,json=nulledFields" json:"nulled_fields,omitempty"`
	DiffFields         []string               `protobuf:"bytes,14,rep,name=diff_fields,json=diffFields" json:"diff_fields,omitempty"`
	RecordDataJson     *string                `protobuf:"bytes,10,opt,name=record_data_json,json=recordDataJson" json:"record_data_json,omitempty"`
	PayloadBinary      []byte                 `protobuf:"bytes,15,opt,name=payload_binary,json=payloadBinary" json:"payload_binary,omitempty"` // raw Avro payload
	SchemaJson         *string                `protobuf:"bytes,16,opt,name=schema_json,json=schemaJson" json:"schema_json,omitempty"`          // Avro schema for payload_binary
	OrgId              *string                `protobuf:"bytes,11,opt,name=org_id,json=orgId" json:"org_id,omitempty"`
	ProcessedTimestamp *int64                 `protobuf:"varint,12,opt,name=processed_timestamp,json=processedTimestamp" json:"processed_timestamp,omitempty"`
	// Multi-tenant additions (go_salesforce_zerobus).
	Topic          *string `protobuf:"bytes,17,opt,name=topic" json:"topic,omitempty"`                                          // e.g. /data/AccountChangeEvent
	TenantKey      *string `protobuf:"bytes,18,opt,name=tenant_key,json=tenantKey" json:"tenant_key,omitempty"`                 // tenant key from tenants.yaml
	DecodeError    *string `protobuf:"bytes,19,opt,name=decode_error,json=decodeError" json:"decode_error,omitempty"`           // set when the payload could not be decoded or the row was truncated
	CommitNumber   *int64  `protobuf:"varint,20,opt,name=commit_number,json=commitNumber" json:"commit_number,omitempty"`       // ChangeEventHeader.commitNumber
	SequenceNumber *int32  `protobuf:"varint,21,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"` // ChangeEventHeader.sequenceNumber
	TransactionKey *string `protobuf:"bytes,22,opt,name=transaction_key,json=transactionKey" json:"transaction_key,omitempty"`  // ChangeEventHeader.transactionKey
	CommitUser     *string `protobuf:"bytes,23,opt,name=commit_user,json=commitUser" json:"commit_user,omitempty"`              // ChangeEventHeader.commitUser
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SalesforceEvent) Reset() {
	*x = SalesforceEvent{}
	mi := &file_salesforce_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalesforceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalesforceEvent) ProtoMessage() {}

func (x *SalesforceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_salesforce_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalesforceEvent.ProtoReflect.Descriptor instead.
func (*SalesforceEvent) Descriptor() ([]byte, []int) {
	return file_salesforce_events_proto_rawDescGZIP(), []int{0}
}

func (x *SalesforceEvent) GetEventId() string {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return ""
}

func (x *SalesforceEvent) GetSchemaId() string {
	if x != nil && x.SchemaId != nil {
		return *x.SchemaId
	}
	return ""
}

func (x *SalesforceEvent) GetReplayId() string {
	if x != nil && x.ReplayId != nil {
		return *x.ReplayId
	}
	return ""
}

func (x *SalesforceEvent) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *SalesforceEvent) GetChangeType() string {
	if x != nil && x.ChangeType != nil {
		return *x.ChangeType
	}
	return ""
}

func (x *SalesforceEvent) GetEntityName() string {
	if x != nil && x.EntityName != nil {
		return *x.EntityName
	}
	return ""
}

func (x *SalesforceEvent) GetChangeOrigin() string {
	if x != nil && x.ChangeOrigin != nil {
		return *x.ChangeOrigin
	}
	return ""
}

func (x *SalesforceEvent) GetRecordIds() []string {
	if x != nil {
		return x.RecordIds
	}
	return nil
}

func (x *SalesforceEvent) GetChangedFields() []string {
	if x != nil {
		return x.ChangedFields
	}
	return nil
}

func (x *SalesforceEvent) GetNulledFields() []string {
	if x != nil {
		return x.NulledFields
	}
	return nil
}

func (x *SalesforceEvent) GetDiffFields() []string {
	if x != nil {
		return x.DiffFields
	}
	return nil
}

func (x *SalesforceEvent) GetRecordDataJson() string {
	if x != nil && x.RecordDataJson != nil {
		return *x.RecordDataJson
	}
	return ""
}

func (x *SalesforceEvent) GetPayloadBinary() []byte {
	if x != nil {
		return x.PayloadBinary
	}
	return nil
}

func (x *SalesforceEvent) GetSchemaJson() string {
	if x != nil && x.SchemaJson != nil {
		return *x.SchemaJson
	}
	return ""
}

func (x *SalesforceEvent) GetOrgId() string {
	if x != nil && x.OrgId != nil {
		return *x.OrgId
	}
	return ""
}

func (x *SalesforceEvent) GetProcessedTimestamp() int64 {
	if x != nil && x.ProcessedTimestamp != nil {
		return *x.ProcessedTimestamp
	}
	return 0
}

func (x *SalesforceEvent) GetTopic() string {
	if x != nil && x.Topic != nil {
		return *x.Topic
	}
	return ""
}

func (x *SalesforceEvent) GetTenantKey() string {
	if x != nil && x.TenantKey != nil {
		return *x.TenantKey
	}
	return ""
}

func (x *SalesforceEvent) GetDecodeError() string {
	if x != nil && x.DecodeError != nil {
		return *x.DecodeError
	}
	return ""
}

func (x *SalesforceEvent) GetCommitNumber() int64 {
	if x != nil && x.CommitNumber != nil {
		return *x.CommitNumber
	}
	return 0
}

func (x *SalesforceEvent) GetSequenceNumber() int32 {
	if x != nil && x.SequenceNumber != nil {
		return *x.SequenceNumber
	}
	return 0
}

func (x *SalesforceEvent) GetTransactionKey() string {
	if x != nil && x.TransactionKey != nil {
		return *x.TransactionKey
	}
	return ""
}

func (x *SalesforceEvent) GetCommitUser() string {
	if x != nil && x.CommitUser != nil {
		return *x.CommitUser
	}
	return ""
}

var File_salesforce_events_proto protoreflect.FileDescriptor

const file_salesforce_events_proto_rawDesc = "" +
	"\n" +
	"\x17salesforce_events.proto\x12\x11salesforce_events\"\xa1\x06\n" +
	"\x0fSalesforceEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\tschema_id\x18\x02 \x01(\tR\bschemaId\x12\x1b\n" +
	"\treplay_id\x18\x03 \x01(\tR\breplayId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vchange_type\x18\x05 \x01(\tR\n" +
	"changeType\x12\x1f\n" +
	"\ventity_name\x18\x06 \x01(\tR\n" +
	"entityName\x12#\n" +
	"\rchange_origin\x18\a \x01(\tR\fchangeOrigin\x12\x1d\n" +
	"\n" +
	"record_ids\x18\b \x03(\tR\trecordIds\x12%\n" +
	"\x0echanged_fields\x18\t \x03(\tR\rchangedFields\x12#\n" +
	"\rnulled_fields\x18\r \x03(\tR\fnulledFields\x12\x1f\n" +
	"\vdiff_fields\x18\x0e \x03(\tR\n" +
	"diffFields\x12(\n" +
	"\x10record_data_json\x18\n" +
	" \x01(\tR\x0erecordDataJson\x12%\n" +
	"\x0epayload_binary\x18\x0f \x01(\fR\rpayloadBinary\x12\x1f\n" +
	"\vschema_json\x18\x10 \x01(\tR\n" +
	"schemaJson\x12\x15\n" +
	"\x06org_id\x18\v \x01(\tR\x05orgId\x12/\n" +
	"\x13processed_timestamp\x18\f \x01(\x03R\x12processedTimestamp\x12\x14\n" +
	"\x05topic\x18\x11 \x01(\tR\x05topic\x12\x1d\n" +
	"\n" +
	"tenant_key\x18\x12 \x01(\tR\ttenantKey\x12!\n" +
	"\fdecode_error\x18\x13 \x01(\tR\vdecodeError\x12#\n" +
	"\rcommit_number\x18\x14 \x01(\x03R\fcommitNumber\x12'\n" +
	"\x0fsequence_number\x18\x15 \x01(\x05R\x0esequenceNumber\x12'\n" +
	"\x0ftransaction_key\x18\x16 \x01(\tR\x0etransactionKey\x12\x1f\n" +
	"\vcommit_user\x18\x17 \x01(\tR\n" +
	"commitUserBXZVgithub.com/databricks-solutions/salesforce-zerobus/go_salesforce_zerobus/proto/eventpb"

var (
	file_salesforce_events_proto_rawDescOnce sync.Once
	file_salesforce_events_proto_rawDescData []byte
)

func file_salesforce_events_proto_rawDescGZIP() []byte {
	file_salesforce_events_proto_rawDescOnce.Do(func() {
		file_salesforce_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_salesforce_events_proto_rawDesc), len(file_salesforce_events_proto_rawDesc)))
	})
	return file_salesforce_events_proto_rawDescData
}

var file_salesforce_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_salesforce_events_proto_goTypes = []any{
	(*SalesforceEvent)(nil), // 0: salesforce_events.SalesforceEvent
}
var file_salesforce_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_salesforce_events_proto_init() }
func file_salesforce_events_proto_init() {
	if File_salesforce_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_salesforce_events_proto_rawDesc), len(file_salesforce_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_salesforce_events_proto_goTypes,
		DependencyIndexes: file_salesforce_events_proto_depIdxs,
		MessageInfos:      file_salesforce_events_proto_msgTypes,
	}.Build()
	File_salesforce_events_proto = out.File
	file_salesforce_events_proto_goTypes = nil
	file_salesforce_events_proto_depIdxs = nil
}
